# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 22:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='birthdate',
            field=models.DateField(null=True),
        ),
    ]
