# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 23:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_registration_birthdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='about_other',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='accessibility',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='after_contact_email',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='registration',
            name='after_contact_facebook',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='registration',
            name='after_contact_messenger',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='registration',
            name='after_contact_other',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='after_contact_person',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='registration',
            name='after_contact_phone',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='registration',
            name='after_contact_skype',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='registration',
            name='after_contact_text',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='registration',
            name='after_social',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='registration',
            name='allergies',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='colitis',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='registration',
            name='condition_active',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='registration',
            name='contact_pref',
            field=models.CharField(choices=[('Phone', 'Phone'), ('E-mail', 'E-mail')], max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='counsellor',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='registration',
            name='crohns',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='registration',
            name='describe_word_1',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='describe_word_2',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='describe_word_3',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='emergency_contact_email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='emergency_contact_first',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='emergency_contact_last',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='emergency_contact_phone',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='endocrinologist',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='registration',
            name='gastroenterologist',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='registration',
            name='gender_preference',
            field=models.CharField(choices=[('no', "It doesn't matter"), ('male', 'Yes, I would prefer a male mentor/mentee'), ('female', 'Yes, I would prefer a female mentor/mentee')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='general_practitioner',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='registration',
            name='gluten_free',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='registration',
            name='hobbies',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='how_managing',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='immunologist',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='registration',
            name='lunch',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='mentor_interest',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='registration',
            name='mood',
            field=models.CharField(choices=[('happy', 'I am happy for most of each day'), ('content', 'I am content for most of each day'), ('sad', 'I am sad for most of each day'), ('very sad', 'I am very sad most of the day')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='music',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='neurologist',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='registration',
            name='nutritionist',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='registration',
            name='other',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='other_specialist',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='pediatrician',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='registration',
            name='perfect_day',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='phone',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='postal_code',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='psychiatrist',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='registration',
            name='psychologist',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='registration',
            name='research_interest',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='registration',
            name='severity',
            field=models.CharField(choices=[('Extremely Severe', 'Extremely Severe'), ('Very Severe', 'Very Severe'), ('Moderately Severe', 'Moderately Severe'), ('Slightly Severe', 'Slightly Severe'), ('Not Severe', 'Not Severe')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='surgeon',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='registration',
            name='surgeries',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='first_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Prefer not to say', 'Prefer not to say')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='gender_identity',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
